#!/usr/bin/python

import smbus
import time
import datetime


bus = smbus.SMBus(1)

#I2C addres
address = 0x4d


filterArray = [0 , 0, 0 , 0 , 0, 0, 0, 0] #holds the filter values 


def filter(input_value):
	filterArray.append(input_value);
	filterArray.pop(0);
	result = (filterArray[0] + filterArray[1]+ filterArray[2]+ filterArray[3]+ filterArray[4]+ filterArray[5]+ filterArray[6]+ filterArray[7])/8 ;
	stringFilterArray = [str(a) for a in filterArray];
	#print(", ".join(stringFilterArray)); 
	return result;



def get_celsius_val(): 
	data = bus.read_i2c_block_data(address, 1,2)
	val = (data[0] << 8) + data[1]
	tCorrectionF = 5/9 * -57
	return val/5.00 + tCorrectionC


while 1 == 1:
	temperature = get_celsius_val()
	filtered_temperature = filter(temperature);
	print filtered_temperature
	time.sleep(0.1)
